export const RECEIVE_NOTEBOOK = "RECEIVE_NOTEBOOK";
export const REQUEST_NOTEBOOK = "REQUEST_NOTEBOOK";
export const REQUEST_CONTENTS = "REQUEST_CONTENTS";
export const RECEIVE_CONTENTS = "RECEIVE_CONTENTS";
export const FETCH_NOTEBOOK = "FETCH_NOTEBOOK";
export const FETCH_CONTENTS = "FETCH_CONTENTS";
