export const REQUEST_CONTENTS = "REQUEST_CONTENTS";
export const RECEIVE_CONTENTS = "RECEIVE_CONTENTS";
export const FETCH_CONTENTS = "FETCH_CONTENTS";
export const RECEIVE_DISCOVERY_RESULTS = "RECEIVE_DISCOVERY_RESULTS";
