// flow-typed signature: 147b201f7481355392cdd20bc2a16a27
// flow-typed version: <<STUB>>/bodybuilder_v^2.0.0/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bodybuilder'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module "bodybuilder" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "bodybuilder/browser/bodybuilder.min" {
  declare module.exports: any;
}

declare module "bodybuilder/lib/aggregation-builder" {
  declare module.exports: any;
}

declare module "bodybuilder/lib/bool-query" {
  declare module.exports: any;
}

declare module "bodybuilder/lib/filter-builder" {
  declare module.exports: any;
}

declare module "bodybuilder/lib/index" {
  declare module.exports: any;
}

declare module "bodybuilder/lib/query-builder" {
  declare module.exports: any;
}

declare module "bodybuilder/lib/utils" {
  declare module.exports: any;
}

declare module "bodybuilder/repl" {
  declare module.exports: any;
}

declare module "bodybuilder/src/aggregation-builder" {
  declare module.exports: any;
}

declare module "bodybuilder/src/bool-query" {
  declare module.exports: any;
}

declare module "bodybuilder/src/filter-builder" {
  declare module.exports: any;
}

declare module "bodybuilder/src/index" {
  declare module.exports: any;
}

declare module "bodybuilder/src/query-builder" {
  declare module.exports: any;
}

declare module "bodybuilder/src/utils" {
  declare module.exports: any;
}

// Filename aliases
declare module "bodybuilder/browser/bodybuilder.min.js" {
  declare module.exports: $Exports<"bodybuilder/browser/bodybuilder.min">;
}
declare module "bodybuilder/lib/aggregation-builder.js" {
  declare module.exports: $Exports<"bodybuilder/lib/aggregation-builder">;
}
declare module "bodybuilder/lib/bool-query.js" {
  declare module.exports: $Exports<"bodybuilder/lib/bool-query">;
}
declare module "bodybuilder/lib/filter-builder.js" {
  declare module.exports: $Exports<"bodybuilder/lib/filter-builder">;
}
declare module "bodybuilder/lib/index.js" {
  declare module.exports: $Exports<"bodybuilder/lib/index">;
}
declare module "bodybuilder/lib/query-builder.js" {
  declare module.exports: $Exports<"bodybuilder/lib/query-builder">;
}
declare module "bodybuilder/lib/utils.js" {
  declare module.exports: $Exports<"bodybuilder/lib/utils">;
}
declare module "bodybuilder/repl.js" {
  declare module.exports: $Exports<"bodybuilder/repl">;
}
declare module "bodybuilder/src/aggregation-builder.js" {
  declare module.exports: $Exports<"bodybuilder/src/aggregation-builder">;
}
declare module "bodybuilder/src/bool-query.js" {
  declare module.exports: $Exports<"bodybuilder/src/bool-query">;
}
declare module "bodybuilder/src/filter-builder.js" {
  declare module.exports: $Exports<"bodybuilder/src/filter-builder">;
}
declare module "bodybuilder/src/index.js" {
  declare module.exports: $Exports<"bodybuilder/src/index">;
}
declare module "bodybuilder/src/query-builder.js" {
  declare module.exports: $Exports<"bodybuilder/src/query-builder">;
}
declare module "bodybuilder/src/utils.js" {
  declare module.exports: $Exports<"bodybuilder/src/utils">;
}
