// flow-typed signature: f5f482c4f3d4d749a2150a9d7c1a343b
// flow-typed version: <<STUB>>/d3-dsv_v^1.0.7/flow_v0.54.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'd3-dsv'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'd3-dsv' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'd3-dsv/build/d3-dsv' {
  declare module.exports: any;
}

declare module 'd3-dsv/build/d3-dsv.min' {
  declare module.exports: any;
}

declare module 'd3-dsv/rollup.config' {
  declare module.exports: any;
}

declare module 'd3-dsv/src/csv' {
  declare module.exports: any;
}

declare module 'd3-dsv/src/dsv' {
  declare module.exports: any;
}

declare module 'd3-dsv/src/tsv' {
  declare module.exports: any;
}

// Filename aliases
declare module 'd3-dsv/build/d3-dsv.js' {
  declare module.exports: $Exports<'d3-dsv/build/d3-dsv'>;
}
declare module 'd3-dsv/build/d3-dsv.min.js' {
  declare module.exports: $Exports<'d3-dsv/build/d3-dsv.min'>;
}
declare module 'd3-dsv/index' {
  declare module.exports: $Exports<'d3-dsv'>;
}
declare module 'd3-dsv/index.js' {
  declare module.exports: $Exports<'d3-dsv'>;
}
declare module 'd3-dsv/rollup.config.js' {
  declare module.exports: $Exports<'d3-dsv/rollup.config'>;
}
declare module 'd3-dsv/src/csv.js' {
  declare module.exports: $Exports<'d3-dsv/src/csv'>;
}
declare module 'd3-dsv/src/dsv.js' {
  declare module.exports: $Exports<'d3-dsv/src/dsv'>;
}
declare module 'd3-dsv/src/tsv.js' {
  declare module.exports: $Exports<'d3-dsv/src/tsv'>;
}
