// flow-typed signature: 81b871b41862f9e0abe63c294f68e0c3
// flow-typed version: <<STUB>>/log_v^1.4.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'log'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "log" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "log/examples/file" {
  declare module.exports: any;
}

declare module "log/examples/reader" {
  declare module.exports: any;
}

declare module "log/examples/stdout" {
  declare module.exports: any;
}

declare module "log/lib/log" {
  declare module.exports: any;
}

// Filename aliases
declare module "log/examples/file.js" {
  declare module.exports: $Exports<"log/examples/file">;
}
declare module "log/examples/reader.js" {
  declare module.exports: $Exports<"log/examples/reader">;
}
declare module "log/examples/stdout.js" {
  declare module.exports: $Exports<"log/examples/stdout">;
}
declare module "log/index" {
  declare module.exports: $Exports<"log">;
}
declare module "log/index.js" {
  declare module.exports: $Exports<"log">;
}
declare module "log/lib/log.js" {
  declare module.exports: $Exports<"log/lib/log">;
}
