// flow-typed signature: 45b4a0d3cc67f1b53d87f27a7d1d491b
// flow-typed version: <<STUB>>/nbschema_v^0.1.0/flow_v0.54.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'nbschema'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'nbschema' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'nbschema/index' {
  declare module.exports: $Exports<'nbschema'>;
}
declare module 'nbschema/index.js' {
  declare module.exports: $Exports<'nbschema'>;
}
