// flow-typed signature: b271ba8d9049b38db971324b10f4f6ef
// flow-typed version: <<STUB>>/nbschema_v^0.1.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'nbschema'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "nbschema" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module "nbschema/index" {
  declare module.exports: $Exports<"nbschema">;
}
declare module "nbschema/index.js" {
  declare module.exports: $Exports<"nbschema">;
}
