// flow-typed signature: 3c8ceb80018724e5f372cc555e40609a
// flow-typed version: <<STUB>>/react-timeago_v3.3.0/flow_v0.50.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-timeago'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "react-timeago" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "react-timeago/lib/dateParser" {
  declare module.exports: any;
}

declare module "react-timeago/lib/defaultFormatter" {
  declare module.exports: any;
}

declare module "react-timeago/lib/formatters/buildFormatter" {
  declare module.exports: any;
}

declare module "react-timeago/lib/index" {
  declare module.exports: any;
}

declare module "react-timeago/lib/language-strings/af" {
  declare module.exports: any;
}

declare module "react-timeago/lib/language-strings/ar" {
  declare module.exports: any;
}

declare module "react-timeago/lib/language-strings/az-short" {
  declare module.exports: any;
}

declare module "react-timeago/lib/language-strings/az" {
  declare module.exports: any;
}

declare module "react-timeago/lib/language-strings/bg" {
  declare module.exports: any;
}

declare module "react-timeago/lib/language-strings/bs" {
  declare module.exports: any;
}

declare module "react-timeago/lib/language-strings/ca" {
  declare module.exports: any;
}

declare module "react-timeago/lib/language-strings/cs" {
  declare module.exports: any;
}

declare module "react-timeago/lib/language-strings/cy" {
  declare module.exports: any;
}

declare module "react-timeago/lib/language-strings/da" {
  declare module.exports: any;
}

declare module "react-timeago/lib/language-strings/de-short" {
  declare module.exports: any;
}

declare module "react-timeago/lib/language-strings/de" {
  declare module.exports: any;
}

declare module "react-timeago/lib/language-strings/dv" {
  declare module.exports: any;
}

declare module "react-timeago/lib/language-strings/el" {
  declare module.exports: any;
}

declare module "react-timeago/lib/language-strings/en-short" {
  declare module.exports: any;
}

declare module "react-timeago/lib/language-strings/en" {
  declare module.exports: any;
}

declare module "react-timeago/lib/language-strings/es-short" {
  declare module.exports: any;
}

declare module "react-timeago/lib/language-strings/es" {
  declare module.exports: any;
}

declare module "react-timeago/lib/language-strings/et" {
  declare module.exports: any;
}

declare module "react-timeago/lib/language-strings/eu" {
  declare module.exports: any;
}

declare module "react-timeago/lib/language-strings/fa-short" {
  declare module.exports: any;
}

declare module "react-timeago/lib/language-strings/fa" {
  declare module.exports: any;
}

declare module "react-timeago/lib/language-strings/fi" {
  declare module.exports: any;
}

declare module "react-timeago/lib/language-strings/fr-short" {
  declare module.exports: any;
}

declare module "react-timeago/lib/language-strings/fr" {
  declare module.exports: any;
}

declare module "react-timeago/lib/language-strings/gl" {
  declare module.exports: any;
}

declare module "react-timeago/lib/language-strings/he" {
  declare module.exports: any;
}

declare module "react-timeago/lib/language-strings/hr" {
  declare module.exports: any;
}

declare module "react-timeago/lib/language-strings/hu" {
  declare module.exports: any;
}

declare module "react-timeago/lib/language-strings/hy" {
  declare module.exports: any;
}

declare module "react-timeago/lib/language-strings/id" {
  declare module.exports: any;
}

declare module "react-timeago/lib/language-strings/is" {
  declare module.exports: any;
}

declare module "react-timeago/lib/language-strings/it-short" {
  declare module.exports: any;
}

declare module "react-timeago/lib/language-strings/it" {
  declare module.exports: any;
}

declare module "react-timeago/lib/language-strings/ja" {
  declare module.exports: any;
}

declare module "react-timeago/lib/language-strings/jv" {
  declare module.exports: any;
}

declare module "react-timeago/lib/language-strings/ko" {
  declare module.exports: any;
}

declare module "react-timeago/lib/language-strings/ky" {
  declare module.exports: any;
}

declare module "react-timeago/lib/language-strings/lt" {
  declare module.exports: any;
}

declare module "react-timeago/lib/language-strings/lv" {
  declare module.exports: any;
}

declare module "react-timeago/lib/language-strings/mk" {
  declare module.exports: any;
}

declare module "react-timeago/lib/language-strings/nl" {
  declare module.exports: any;
}

declare module "react-timeago/lib/language-strings/no" {
  declare module.exports: any;
}

declare module "react-timeago/lib/language-strings/pl" {
  declare module.exports: any;
}

declare module "react-timeago/lib/language-strings/pt-br-short" {
  declare module.exports: any;
}

declare module "react-timeago/lib/language-strings/pt-br" {
  declare module.exports: any;
}

declare module "react-timeago/lib/language-strings/pt-short" {
  declare module.exports: any;
}

declare module "react-timeago/lib/language-strings/pt" {
  declare module.exports: any;
}

declare module "react-timeago/lib/language-strings/ro" {
  declare module.exports: any;
}

declare module "react-timeago/lib/language-strings/rs" {
  declare module.exports: any;
}

declare module "react-timeago/lib/language-strings/ru" {
  declare module.exports: any;
}

declare module "react-timeago/lib/language-strings/rw" {
  declare module.exports: any;
}

declare module "react-timeago/lib/language-strings/si" {
  declare module.exports: any;
}

declare module "react-timeago/lib/language-strings/sk" {
  declare module.exports: any;
}

declare module "react-timeago/lib/language-strings/sl" {
  declare module.exports: any;
}

declare module "react-timeago/lib/language-strings/sr" {
  declare module.exports: any;
}

declare module "react-timeago/lib/language-strings/sv" {
  declare module.exports: any;
}

declare module "react-timeago/lib/language-strings/th" {
  declare module.exports: any;
}

declare module "react-timeago/lib/language-strings/tr-short" {
  declare module.exports: any;
}

declare module "react-timeago/lib/language-strings/tr" {
  declare module.exports: any;
}

declare module "react-timeago/lib/language-strings/uk" {
  declare module.exports: any;
}

declare module "react-timeago/lib/language-strings/uz" {
  declare module.exports: any;
}

declare module "react-timeago/lib/language-strings/vi" {
  declare module.exports: any;
}

declare module "react-timeago/lib/language-strings/zh-CN" {
  declare module.exports: any;
}

declare module "react-timeago/lib/language-strings/zh-TW" {
  declare module.exports: any;
}

declare module "react-timeago/test/index" {
  declare module.exports: any;
}

// Filename aliases
declare module "react-timeago/lib/dateParser.js" {
  declare module.exports: $Exports<"react-timeago/lib/dateParser">;
}
declare module "react-timeago/lib/defaultFormatter.js" {
  declare module.exports: $Exports<"react-timeago/lib/defaultFormatter">;
}
declare module "react-timeago/lib/formatters/buildFormatter.js" {
  declare module.exports: $Exports<
    "react-timeago/lib/formatters/buildFormatter"
  >;
}
declare module "react-timeago/lib/index.js" {
  declare module.exports: $Exports<"react-timeago/lib/index">;
}
declare module "react-timeago/lib/language-strings/af.js" {
  declare module.exports: $Exports<"react-timeago/lib/language-strings/af">;
}
declare module "react-timeago/lib/language-strings/ar.js" {
  declare module.exports: $Exports<"react-timeago/lib/language-strings/ar">;
}
declare module "react-timeago/lib/language-strings/az-short.js" {
  declare module.exports: $Exports<
    "react-timeago/lib/language-strings/az-short"
  >;
}
declare module "react-timeago/lib/language-strings/az.js" {
  declare module.exports: $Exports<"react-timeago/lib/language-strings/az">;
}
declare module "react-timeago/lib/language-strings/bg.js" {
  declare module.exports: $Exports<"react-timeago/lib/language-strings/bg">;
}
declare module "react-timeago/lib/language-strings/bs.js" {
  declare module.exports: $Exports<"react-timeago/lib/language-strings/bs">;
}
declare module "react-timeago/lib/language-strings/ca.js" {
  declare module.exports: $Exports<"react-timeago/lib/language-strings/ca">;
}
declare module "react-timeago/lib/language-strings/cs.js" {
  declare module.exports: $Exports<"react-timeago/lib/language-strings/cs">;
}
declare module "react-timeago/lib/language-strings/cy.js" {
  declare module.exports: $Exports<"react-timeago/lib/language-strings/cy">;
}
declare module "react-timeago/lib/language-strings/da.js" {
  declare module.exports: $Exports<"react-timeago/lib/language-strings/da">;
}
declare module "react-timeago/lib/language-strings/de-short.js" {
  declare module.exports: $Exports<
    "react-timeago/lib/language-strings/de-short"
  >;
}
declare module "react-timeago/lib/language-strings/de.js" {
  declare module.exports: $Exports<"react-timeago/lib/language-strings/de">;
}
declare module "react-timeago/lib/language-strings/dv.js" {
  declare module.exports: $Exports<"react-timeago/lib/language-strings/dv">;
}
declare module "react-timeago/lib/language-strings/el.js" {
  declare module.exports: $Exports<"react-timeago/lib/language-strings/el">;
}
declare module "react-timeago/lib/language-strings/en-short.js" {
  declare module.exports: $Exports<
    "react-timeago/lib/language-strings/en-short"
  >;
}
declare module "react-timeago/lib/language-strings/en.js" {
  declare module.exports: $Exports<"react-timeago/lib/language-strings/en">;
}
declare module "react-timeago/lib/language-strings/es-short.js" {
  declare module.exports: $Exports<
    "react-timeago/lib/language-strings/es-short"
  >;
}
declare module "react-timeago/lib/language-strings/es.js" {
  declare module.exports: $Exports<"react-timeago/lib/language-strings/es">;
}
declare module "react-timeago/lib/language-strings/et.js" {
  declare module.exports: $Exports<"react-timeago/lib/language-strings/et">;
}
declare module "react-timeago/lib/language-strings/eu.js" {
  declare module.exports: $Exports<"react-timeago/lib/language-strings/eu">;
}
declare module "react-timeago/lib/language-strings/fa-short.js" {
  declare module.exports: $Exports<
    "react-timeago/lib/language-strings/fa-short"
  >;
}
declare module "react-timeago/lib/language-strings/fa.js" {
  declare module.exports: $Exports<"react-timeago/lib/language-strings/fa">;
}
declare module "react-timeago/lib/language-strings/fi.js" {
  declare module.exports: $Exports<"react-timeago/lib/language-strings/fi">;
}
declare module "react-timeago/lib/language-strings/fr-short.js" {
  declare module.exports: $Exports<
    "react-timeago/lib/language-strings/fr-short"
  >;
}
declare module "react-timeago/lib/language-strings/fr.js" {
  declare module.exports: $Exports<"react-timeago/lib/language-strings/fr">;
}
declare module "react-timeago/lib/language-strings/gl.js" {
  declare module.exports: $Exports<"react-timeago/lib/language-strings/gl">;
}
declare module "react-timeago/lib/language-strings/he.js" {
  declare module.exports: $Exports<"react-timeago/lib/language-strings/he">;
}
declare module "react-timeago/lib/language-strings/hr.js" {
  declare module.exports: $Exports<"react-timeago/lib/language-strings/hr">;
}
declare module "react-timeago/lib/language-strings/hu.js" {
  declare module.exports: $Exports<"react-timeago/lib/language-strings/hu">;
}
declare module "react-timeago/lib/language-strings/hy.js" {
  declare module.exports: $Exports<"react-timeago/lib/language-strings/hy">;
}
declare module "react-timeago/lib/language-strings/id.js" {
  declare module.exports: $Exports<"react-timeago/lib/language-strings/id">;
}
declare module "react-timeago/lib/language-strings/is.js" {
  declare module.exports: $Exports<"react-timeago/lib/language-strings/is">;
}
declare module "react-timeago/lib/language-strings/it-short.js" {
  declare module.exports: $Exports<
    "react-timeago/lib/language-strings/it-short"
  >;
}
declare module "react-timeago/lib/language-strings/it.js" {
  declare module.exports: $Exports<"react-timeago/lib/language-strings/it">;
}
declare module "react-timeago/lib/language-strings/ja.js" {
  declare module.exports: $Exports<"react-timeago/lib/language-strings/ja">;
}
declare module "react-timeago/lib/language-strings/jv.js" {
  declare module.exports: $Exports<"react-timeago/lib/language-strings/jv">;
}
declare module "react-timeago/lib/language-strings/ko.js" {
  declare module.exports: $Exports<"react-timeago/lib/language-strings/ko">;
}
declare module "react-timeago/lib/language-strings/ky.js" {
  declare module.exports: $Exports<"react-timeago/lib/language-strings/ky">;
}
declare module "react-timeago/lib/language-strings/lt.js" {
  declare module.exports: $Exports<"react-timeago/lib/language-strings/lt">;
}
declare module "react-timeago/lib/language-strings/lv.js" {
  declare module.exports: $Exports<"react-timeago/lib/language-strings/lv">;
}
declare module "react-timeago/lib/language-strings/mk.js" {
  declare module.exports: $Exports<"react-timeago/lib/language-strings/mk">;
}
declare module "react-timeago/lib/language-strings/nl.js" {
  declare module.exports: $Exports<"react-timeago/lib/language-strings/nl">;
}
declare module "react-timeago/lib/language-strings/no.js" {
  declare module.exports: $Exports<"react-timeago/lib/language-strings/no">;
}
declare module "react-timeago/lib/language-strings/pl.js" {
  declare module.exports: $Exports<"react-timeago/lib/language-strings/pl">;
}
declare module "react-timeago/lib/language-strings/pt-br-short.js" {
  declare module.exports: $Exports<
    "react-timeago/lib/language-strings/pt-br-short"
  >;
}
declare module "react-timeago/lib/language-strings/pt-br.js" {
  declare module.exports: $Exports<"react-timeago/lib/language-strings/pt-br">;
}
declare module "react-timeago/lib/language-strings/pt-short.js" {
  declare module.exports: $Exports<
    "react-timeago/lib/language-strings/pt-short"
  >;
}
declare module "react-timeago/lib/language-strings/pt.js" {
  declare module.exports: $Exports<"react-timeago/lib/language-strings/pt">;
}
declare module "react-timeago/lib/language-strings/ro.js" {
  declare module.exports: $Exports<"react-timeago/lib/language-strings/ro">;
}
declare module "react-timeago/lib/language-strings/rs.js" {
  declare module.exports: $Exports<"react-timeago/lib/language-strings/rs">;
}
declare module "react-timeago/lib/language-strings/ru.js" {
  declare module.exports: $Exports<"react-timeago/lib/language-strings/ru">;
}
declare module "react-timeago/lib/language-strings/rw.js" {
  declare module.exports: $Exports<"react-timeago/lib/language-strings/rw">;
}
declare module "react-timeago/lib/language-strings/si.js" {
  declare module.exports: $Exports<"react-timeago/lib/language-strings/si">;
}
declare module "react-timeago/lib/language-strings/sk.js" {
  declare module.exports: $Exports<"react-timeago/lib/language-strings/sk">;
}
declare module "react-timeago/lib/language-strings/sl.js" {
  declare module.exports: $Exports<"react-timeago/lib/language-strings/sl">;
}
declare module "react-timeago/lib/language-strings/sr.js" {
  declare module.exports: $Exports<"react-timeago/lib/language-strings/sr">;
}
declare module "react-timeago/lib/language-strings/sv.js" {
  declare module.exports: $Exports<"react-timeago/lib/language-strings/sv">;
}
declare module "react-timeago/lib/language-strings/th.js" {
  declare module.exports: $Exports<"react-timeago/lib/language-strings/th">;
}
declare module "react-timeago/lib/language-strings/tr-short.js" {
  declare module.exports: $Exports<
    "react-timeago/lib/language-strings/tr-short"
  >;
}
declare module "react-timeago/lib/language-strings/tr.js" {
  declare module.exports: $Exports<"react-timeago/lib/language-strings/tr">;
}
declare module "react-timeago/lib/language-strings/uk.js" {
  declare module.exports: $Exports<"react-timeago/lib/language-strings/uk">;
}
declare module "react-timeago/lib/language-strings/uz.js" {
  declare module.exports: $Exports<"react-timeago/lib/language-strings/uz">;
}
declare module "react-timeago/lib/language-strings/vi.js" {
  declare module.exports: $Exports<"react-timeago/lib/language-strings/vi">;
}
declare module "react-timeago/lib/language-strings/zh-CN.js" {
  declare module.exports: $Exports<"react-timeago/lib/language-strings/zh-CN">;
}
declare module "react-timeago/lib/language-strings/zh-TW.js" {
  declare module.exports: $Exports<"react-timeago/lib/language-strings/zh-TW">;
}
declare module "react-timeago/test/index.js" {
  declare module.exports: $Exports<"react-timeago/test/index">;
}
