// flow-typed signature: 5dc51d38b28c2d9b1e8a8d6ad7408109
// flow-typed version: <<STUB>>/rx-jupyter_v^2.0.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rx-jupyter'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "rx-jupyter" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "rx-jupyter/docs/scripts/linenumber" {
  declare module.exports: any;
}

declare module "rx-jupyter/docs/scripts/prettify/lang-css" {
  declare module.exports: any;
}

declare module "rx-jupyter/docs/scripts/prettify/prettify" {
  declare module.exports: any;
}

declare module "rx-jupyter/lib/base" {
  declare module.exports: any;
}

declare module "rx-jupyter/lib/contents" {
  declare module.exports: any;
}

declare module "rx-jupyter/lib/index" {
  declare module.exports: any;
}

declare module "rx-jupyter/lib/kernels" {
  declare module.exports: any;
}

declare module "rx-jupyter/lib/kernelspecs" {
  declare module.exports: any;
}

declare module "rx-jupyter/lib/sessions" {
  declare module.exports: any;
}

declare module "rx-jupyter/lib/terminals" {
  declare module.exports: any;
}

declare module "rx-jupyter/src/base" {
  declare module.exports: any;
}

declare module "rx-jupyter/src/contents" {
  declare module.exports: any;
}

declare module "rx-jupyter/src/index" {
  declare module.exports: any;
}

declare module "rx-jupyter/src/kernels" {
  declare module.exports: any;
}

declare module "rx-jupyter/src/kernelspecs" {
  declare module.exports: any;
}

declare module "rx-jupyter/src/sessions" {
  declare module.exports: any;
}

declare module "rx-jupyter/src/terminals" {
  declare module.exports: any;
}

declare module "rx-jupyter/test/contents-spec" {
  declare module.exports: any;
}

declare module "rx-jupyter/test/index-spec" {
  declare module.exports: any;
}

declare module "rx-jupyter/test/kernel-spec" {
  declare module.exports: any;
}

declare module "rx-jupyter/test/kernelspecs-spec" {
  declare module.exports: any;
}

declare module "rx-jupyter/test/sessions-spec" {
  declare module.exports: any;
}

declare module "rx-jupyter/test/terminals-spec" {
  declare module.exports: any;
}

// Filename aliases
declare module "rx-jupyter/docs/scripts/linenumber.js" {
  declare module.exports: $Exports<"rx-jupyter/docs/scripts/linenumber">;
}
declare module "rx-jupyter/docs/scripts/prettify/lang-css.js" {
  declare module.exports: $Exports<"rx-jupyter/docs/scripts/prettify/lang-css">;
}
declare module "rx-jupyter/docs/scripts/prettify/prettify.js" {
  declare module.exports: $Exports<"rx-jupyter/docs/scripts/prettify/prettify">;
}
declare module "rx-jupyter/lib/base.js" {
  declare module.exports: $Exports<"rx-jupyter/lib/base">;
}
declare module "rx-jupyter/lib/contents.js" {
  declare module.exports: $Exports<"rx-jupyter/lib/contents">;
}
declare module "rx-jupyter/lib/index.js" {
  declare module.exports: $Exports<"rx-jupyter/lib/index">;
}
declare module "rx-jupyter/lib/kernels.js" {
  declare module.exports: $Exports<"rx-jupyter/lib/kernels">;
}
declare module "rx-jupyter/lib/kernelspecs.js" {
  declare module.exports: $Exports<"rx-jupyter/lib/kernelspecs">;
}
declare module "rx-jupyter/lib/sessions.js" {
  declare module.exports: $Exports<"rx-jupyter/lib/sessions">;
}
declare module "rx-jupyter/lib/terminals.js" {
  declare module.exports: $Exports<"rx-jupyter/lib/terminals">;
}
declare module "rx-jupyter/src/base.js" {
  declare module.exports: $Exports<"rx-jupyter/src/base">;
}
declare module "rx-jupyter/src/contents.js" {
  declare module.exports: $Exports<"rx-jupyter/src/contents">;
}
declare module "rx-jupyter/src/index.js" {
  declare module.exports: $Exports<"rx-jupyter/src/index">;
}
declare module "rx-jupyter/src/kernels.js" {
  declare module.exports: $Exports<"rx-jupyter/src/kernels">;
}
declare module "rx-jupyter/src/kernelspecs.js" {
  declare module.exports: $Exports<"rx-jupyter/src/kernelspecs">;
}
declare module "rx-jupyter/src/sessions.js" {
  declare module.exports: $Exports<"rx-jupyter/src/sessions">;
}
declare module "rx-jupyter/src/terminals.js" {
  declare module.exports: $Exports<"rx-jupyter/src/terminals">;
}
declare module "rx-jupyter/test/contents-spec.js" {
  declare module.exports: $Exports<"rx-jupyter/test/contents-spec">;
}
declare module "rx-jupyter/test/index-spec.js" {
  declare module.exports: $Exports<"rx-jupyter/test/index-spec">;
}
declare module "rx-jupyter/test/kernel-spec.js" {
  declare module.exports: $Exports<"rx-jupyter/test/kernel-spec">;
}
declare module "rx-jupyter/test/kernelspecs-spec.js" {
  declare module.exports: $Exports<"rx-jupyter/test/kernelspecs-spec">;
}
declare module "rx-jupyter/test/sessions-spec.js" {
  declare module.exports: $Exports<"rx-jupyter/test/sessions-spec">;
}
declare module "rx-jupyter/test/terminals-spec.js" {
  declare module.exports: $Exports<"rx-jupyter/test/terminals-spec">;
}
