// flow-typed signature: 32061b7a7bf2b8d040f8c905ffd03ae1
// flow-typed version: <<STUB>>/s3-proxy_v^1.1.0/flow_v0.50.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   's3-proxy'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "s3-proxy" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "s3-proxy/lib/s3" {
  declare module.exports: any;
}

// Filename aliases
declare module "s3-proxy/index" {
  declare module.exports: $Exports<"s3-proxy">;
}
declare module "s3-proxy/index.js" {
  declare module.exports: $Exports<"s3-proxy">;
}
declare module "s3-proxy/lib/s3.js" {
  declare module.exports: $Exports<"s3-proxy/lib/s3">;
}
