// flow-typed signature: d6bf78cb6b89b05c38b1fa0f5810dc6d
// flow-typed version: <<STUB>>/styled-jsx_v1.0.6/flow_v0.50.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'styled-jsx'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "styled-jsx" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "styled-jsx/babel" {
  declare module.exports: any;
}

declare module "styled-jsx/dist/_constants" {
  declare module.exports: any;
}

declare module "styled-jsx/dist/_utils" {
  declare module.exports: any;
}

declare module "styled-jsx/dist/babel-external" {
  declare module.exports: any;
}

declare module "styled-jsx/dist/babel" {
  declare module.exports: any;
}

declare module "styled-jsx/dist/lib/style-transform" {
  declare module.exports: any;
}

declare module "styled-jsx/dist/render" {
  declare module.exports: any;
}

declare module "styled-jsx/dist/server" {
  declare module.exports: any;
}

declare module "styled-jsx/dist/style" {
  declare module.exports: any;
}

declare module "styled-jsx/lib/style-transform" {
  declare module.exports: any;
}

declare module "styled-jsx/server" {
  declare module.exports: any;
}

declare module "styled-jsx/style" {
  declare module.exports: any;
}

// Filename aliases
declare module "styled-jsx/babel.js" {
  declare module.exports: $Exports<"styled-jsx/babel">;
}
declare module "styled-jsx/dist/_constants.js" {
  declare module.exports: $Exports<"styled-jsx/dist/_constants">;
}
declare module "styled-jsx/dist/_utils.js" {
  declare module.exports: $Exports<"styled-jsx/dist/_utils">;
}
declare module "styled-jsx/dist/babel-external.js" {
  declare module.exports: $Exports<"styled-jsx/dist/babel-external">;
}
declare module "styled-jsx/dist/babel.js" {
  declare module.exports: $Exports<"styled-jsx/dist/babel">;
}
declare module "styled-jsx/dist/lib/style-transform.js" {
  declare module.exports: $Exports<"styled-jsx/dist/lib/style-transform">;
}
declare module "styled-jsx/dist/render.js" {
  declare module.exports: $Exports<"styled-jsx/dist/render">;
}
declare module "styled-jsx/dist/server.js" {
  declare module.exports: $Exports<"styled-jsx/dist/server">;
}
declare module "styled-jsx/dist/style.js" {
  declare module.exports: $Exports<"styled-jsx/dist/style">;
}
declare module "styled-jsx/lib/style-transform.js" {
  declare module.exports: $Exports<"styled-jsx/lib/style-transform">;
}
declare module "styled-jsx/server.js" {
  declare module.exports: $Exports<"styled-jsx/server">;
}
declare module "styled-jsx/style.js" {
  declare module.exports: $Exports<"styled-jsx/style">;
}
