// flow-typed signature: 0ca0ed95c4217fe928e4a1d2c988976f
// flow-typed version: <<STUB>>/@nteract/commuter-frontend_v^1.7.0/flow_v0.54.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@nteract/commuter-frontend'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@nteract/commuter-frontend' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@nteract/commuter-frontend/components/body' {
  declare module.exports: any;
}

declare module '@nteract/commuter-frontend/components/browse-header' {
  declare module.exports: any;
}

declare module '@nteract/commuter-frontend/components/contents/csv' {
  declare module.exports: any;
}

declare module '@nteract/commuter-frontend/components/contents/directory-listing' {
  declare module.exports: any;
}

declare module '@nteract/commuter-frontend/components/contents/html' {
  declare module.exports: any;
}

declare module '@nteract/commuter-frontend/components/contents/index' {
  declare module.exports: any;
}

declare module '@nteract/commuter-frontend/components/contents/json' {
  declare module.exports: any;
}

declare module '@nteract/commuter-frontend/components/contents/types' {
  declare module.exports: any;
}

declare module '@nteract/commuter-frontend/components/contents/zeppelin' {
  declare module.exports: any;
}

declare module '@nteract/commuter-frontend/components/header' {
  declare module.exports: any;
}

declare module '@nteract/commuter-frontend/pages/_document' {
  declare module.exports: any;
}

declare module '@nteract/commuter-frontend/pages/discover' {
  declare module.exports: any;
}

declare module '@nteract/commuter-frontend/pages/index' {
  declare module.exports: any;
}

declare module '@nteract/commuter-frontend/pages/view' {
  declare module.exports: any;
}

declare module '@nteract/commuter-frontend/theme' {
  declare module.exports: any;
}

declare module '@nteract/commuter-frontend/transforms/index' {
  declare module.exports: any;
}

declare module '@nteract/commuter-frontend/transforms/PlotlyTransform' {
  declare module.exports: any;
}

// Filename aliases
declare module '@nteract/commuter-frontend/components/body.js' {
  declare module.exports: $Exports<'@nteract/commuter-frontend/components/body'>;
}
declare module '@nteract/commuter-frontend/components/browse-header.js' {
  declare module.exports: $Exports<'@nteract/commuter-frontend/components/browse-header'>;
}
declare module '@nteract/commuter-frontend/components/contents/csv.js' {
  declare module.exports: $Exports<'@nteract/commuter-frontend/components/contents/csv'>;
}
declare module '@nteract/commuter-frontend/components/contents/directory-listing.js' {
  declare module.exports: $Exports<'@nteract/commuter-frontend/components/contents/directory-listing'>;
}
declare module '@nteract/commuter-frontend/components/contents/html.js' {
  declare module.exports: $Exports<'@nteract/commuter-frontend/components/contents/html'>;
}
declare module '@nteract/commuter-frontend/components/contents/index.js' {
  declare module.exports: $Exports<'@nteract/commuter-frontend/components/contents/index'>;
}
declare module '@nteract/commuter-frontend/components/contents/json.js' {
  declare module.exports: $Exports<'@nteract/commuter-frontend/components/contents/json'>;
}
declare module '@nteract/commuter-frontend/components/contents/types.js' {
  declare module.exports: $Exports<'@nteract/commuter-frontend/components/contents/types'>;
}
declare module '@nteract/commuter-frontend/components/contents/zeppelin.js' {
  declare module.exports: $Exports<'@nteract/commuter-frontend/components/contents/zeppelin'>;
}
declare module '@nteract/commuter-frontend/components/header.js' {
  declare module.exports: $Exports<'@nteract/commuter-frontend/components/header'>;
}
declare module '@nteract/commuter-frontend/index' {
  declare module.exports: $Exports<'@nteract/commuter-frontend'>;
}
declare module '@nteract/commuter-frontend/index.js' {
  declare module.exports: $Exports<'@nteract/commuter-frontend'>;
}
declare module '@nteract/commuter-frontend/pages/_document.js' {
  declare module.exports: $Exports<'@nteract/commuter-frontend/pages/_document'>;
}
declare module '@nteract/commuter-frontend/pages/discover.js' {
  declare module.exports: $Exports<'@nteract/commuter-frontend/pages/discover'>;
}
declare module '@nteract/commuter-frontend/pages/index.js' {
  declare module.exports: $Exports<'@nteract/commuter-frontend/pages/index'>;
}
declare module '@nteract/commuter-frontend/pages/view.js' {
  declare module.exports: $Exports<'@nteract/commuter-frontend/pages/view'>;
}
declare module '@nteract/commuter-frontend/theme.js' {
  declare module.exports: $Exports<'@nteract/commuter-frontend/theme'>;
}
declare module '@nteract/commuter-frontend/transforms/index.js' {
  declare module.exports: $Exports<'@nteract/commuter-frontend/transforms/index'>;
}
declare module '@nteract/commuter-frontend/transforms/PlotlyTransform.js' {
  declare module.exports: $Exports<'@nteract/commuter-frontend/transforms/PlotlyTransform'>;
}
